---
#- name: debian | Updating APT Cache
#  apt:
#    update_cache: true

- name: debian | Installing Pre-Reqs
  apt:
    name:
      - apt-transport-https
      - gnupg
      - software-properties-common
    state: present
    update_cache: yes

- name: debian | Adding GlusterFS Repo
  apt_repository:
    repo: "ppa:gluster/glusterfs-{{ glusterfs_version }}"
    state: present
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: ansible_distribution == "Ubuntu"

- name: debian | Adding GlusterFS Repo Key
  apt_key:
    url: "{{ glusterfs_debian_repo_key }}"
    state: present
  when: ansible_distribution == "Debian"

- name: debian | Adding GlusterFS Repo
  apt_repository:
    repo: "{{ glusterfs_debian_repo }}"
    state: present
  when: ansible_distribution == "Debian"

- name: debian | Installing glusterfs-server
  package:
    name: "glusterfs-server={{ glusterfs_minor_version }}"
    state: present
