---
- name: redhat | Enabling PowerTools Repo
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_version is version('8', '>=')

- name: redhat | Adding Gluster Repo
  yum:
    name: centos-release-gluster
    state: present
  when: ansible_distribution != "Fedora"

- name: redhat | Installing glusterfs-server
  package:
    name: "glusterfs-server-{{ glusterfs_minor_version }}"
    state: present
